use_frameworks!

target 'CPRadarChartView_Example' do
  pod 'CPRadarChartView', :path => '../'

  target 'CPRadarChartView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
